[workspace]
resolver = "2"

[package]
name = "nativelink"
version = "0.2.0"
edition = "2021"

[profile.release]
lto = true
opt-level = 3

[[bin]]
name = "nativelink"

[features]
enable_tokio_console = []

[dependencies]
nativelink-error = { path = "nativelink-error" }
nativelink-proto = { path = "nativelink-proto" }
nativelink-config = { path = "nativelink-config" }
nativelink-scheduler = { path = "nativelink-scheduler" }
nativelink-service = { path = "nativelink-service" }
nativelink-store = { path = "nativelink-store" }
nativelink-util = { path = "nativelink-util" }
nativelink-worker = { path = "nativelink-worker" }

async-lock = "3.2.0"
axum = "0.6.20"
clap = { version = "4.4.11", features = ["derive"] }
futures = "0.3.29"
hyper = { version = "0.14.27" }
parking_lot = "0.12.1"
prometheus-client = "0.21.2"
rustls-pemfile = "2.0.0"
scopeguard = "1.2.0"
serde_json5 = "0.1.0"
tokio = { version = "1.35.1", features = ["rt-multi-thread", "signal"] }
tokio-rustls = "0.25.0"
tonic = { version = "0.10.2", features = ["gzip"] }
tower = "0.4.13"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
console-subscriber = { version = "0.2.0" }
