---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nativelink-worker-buck2
spec:
  #replicas: 1
  replicas: 20
  selector:
    matchLabels:
      app: nativelink-worker-buck2
  template:
    metadata:
      labels:
        app: nativelink-worker-buck2
    spec:
      initContainers:
        - name: nativelink-worker-init
          # This image will be edited by kustomize.
          image: nativelink-worker-init
          args: ["/shared/nativelink"]
          volumeMounts:
            - name: shared
              mountPath: /shared
      containers:
        - name: nativelink-worker-buck2
          # This image will be edited by kustomize.
          image: nativelink-worker-buck2
          env:
            - name: RUST_LOG
              value: debug,h2=off,tower=off,hyper=off
            - name: CAS_ENDPOINT
              value: nativelink-cas
            - name: SCHEDULER_ENDPOINT
              value: nativelink-scheduler
          volumeMounts:
            - name: worker-config
              mountPath: /worker.json
              subPath: worker.json
            - name: worker-entrypoint
              mountPath: /entrypoint.sh
              subPath: entrypoint.sh
              readOnly: false
            - name: shared
              mountPath: /shared
          command: ["/shared/nativelink"]
          args: ["/worker.json"]
      volumes:
        - name: shared
          emptyDir: {}
        - name: worker-config
          configMap:
            name: worker
        - name: worker-entrypoint
          configMap:
            name: worker
            items:
              - key: entrypoint.sh
                path: entrypoint.sh
                mode: 0777
