[package]
name = "nativelink-store"
version = "0.2.0"
edition = "2021"

[dependencies]
nativelink-error = { path = "../nativelink-error" }
nativelink-config = { path = "../nativelink-config" }
nativelink-util = { path = "../nativelink-util" }
nativelink-proto = { path = "../nativelink-proto" }

async-lock = "3.2.0"
async-trait = "0.1.74"
aws-config = "0.57.2"
aws-sdk-s3 = { version = "0.35.0" }
aws-smithy-runtime = { version = "0.57.2" }
bincode = "1.3.3"
blake3 = "1.5.0"
byteorder = "1.5.0"
bytes = "1.5.0"
filetime = "0.2.23"
futures = "0.3.29"
hex = "0.4.3"
hyper = { version = "0.14.27" }
hyper-rustls = { version = "0.24.2", features = ["webpki-tokio"] }
lz4_flex = "0.11.1"
parking_lot = "0.12.1"
prost = "0.12.3"
rand = "0.8.5"
serde = "1.0.193"
sha2 = "0.10.8"
shellexpand = "3.1.0"
tempfile = "3.9.0"
tokio = { version = "1.35.1" }
tokio-stream = { version = "0.1.14", features = ["fs"] }
tokio-util = { version = "0.7.10" }
tonic = { version = "0.10.2", features = ["gzip", "tls"] }
tracing = "0.1.40"
uuid = { version = "1.6.1", features = ["v4"] }

[dev-dependencies]
pretty_assertions = "1.4.0"
memory-stats = "1.1.0"
once_cell = "1.19.0"
http = "^0.2.11"
aws-smithy-types = "0.57.2"
aws-sdk-s3 = { version = "0.35.0"  }
aws-smithy-runtime = { version = "0.57.2", features = ["test-util"] }
